### ISSUE TITLE
Monochrome icons possible?

### ISSUE THREAD

**Issue by Dom1n1c** [CFenner/MMM-LocalTransport#13]
The thing i mentioned before was, that the icons:
https://maps.gstatic.com/mapfiles/transit/iw2/6/de-metro.png
and
https://maps.gstatic.com/mapfiles/transit/iw2/6/de-sbahn.png
are not monochrome.
Do you think it might be possible, to replace them within the script, to have a clearer mirror design?

**Comment by CFenner** [comment]
You could try the css style `filter: grayscale(100%)` on the images.

**Comment by niklasbeinghaus** [comment]
Related:
I'd like to have a configurable boolean `colored` option for the config.js.
If true: colors are pulled from the API - if possible, let's try to pull the individual colors for the different tram-lines as well.
If false: `filter: grayscale(100%)` in CSS.

I'll try to dive into GMaps API and code it by myself, help is however appreciated since I'm not experienced in using APIs and stuff.

**Comment by GHLasse** [comment]
@niklasbeinghaus can you test the changes I made please? Then @CFenner can merge this :-)

**Comment by GHLasse** [comment]
Ah yes, I forgot about the less file. I think that closes this issue?
